name: default

on:
  push:
    branches:
      - develop
      - broken/seperate-rebase

jobs:
  bom:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c bom.kibot.yaml
      uses: ./
      with:
        config: config/bom.kibot.yaml
        dir: test/output
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: bom"
      run: |
        test -f test/output/docs/bom/*-bom.html && \
        test -f test/output/docs/bom/*-ibom.html && \
        test -f test/output/docs/bom/*-bom.xlsx
    - uses: peter-evans/rebase@v1
      if: ${{ success() }}
      with:
        base: develop
    - name: git commit && git push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ${{ github.workflow }} ${{ github.job }}
        push-branch: 'develop'
        files: test/output/docs/bom/*

  docs:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: bom
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c docs.kibot.yaml
      uses: ./
      with:
        config: config/docs.kibot.yaml
        dir: test/output
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: schematic.svg"
      run: test -f test/output/docs/img/*-schematic.svg
    - name: "check output: schematic.pdf"
      run: test -f test/output/docs/*-schematic.pdf
#    - name: "check output: board.pdf"
#      run: test -f test/output/docs/*-board.pdf
    - uses: peter-evans/rebase@v1
      if: ${{ success() }}
      with:
        base: develop
      - name: git commit && git push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ${{ github.workflow }} ${{ github.job }}
        push-branch: 'develop'
        files: test/output/docs/*

  gerbers:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: docs
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c gerbers.kibot.yaml 
      uses: ./
      with:
        config: config/gerbers.kibot.yaml
        dir: test/output
        board: test/test.kicad_pcb
        schema: test/test.sch
    - name: "check output: gerber"
      run: |
        test -f test/output/gerbers/*B_CrtYd.gbr && \
        test -f test/output/gerbers/*F_CrtYd.gbr && \
        test -f test/output/gerbers/*B_Cu.gbr && \
        test -f test/output/gerbers/*F_Cu.gbr && \
        test -f test/output/gerbers/*B_Mask.gbr && \
        test -f test/output/gerbers/*F_Mask.gbr && \
        test -f test/output/gerbers/*B_Paste.gbr && \
        test -f test/output/gerbers/*F_Paste.gbr && \
        test -f test/output/gerbers/*B_SilkS.gbr && \
        test -f test/output/gerbers/*F_SilkS.gbr && \
        test -f test/output/gerbers/*B_CrtYd.gbr && \
        test -f test/output/gerbers/*F_CrtYd.gbr
    - name: "check output: gerber"
      run: |
        test -f test/output/gerbers/*NPTH_drill.gbr && \
        test -f test/output/gerbers/*NPTH_drill.drl && \
        test -f test/output/gerbers/*PTH_drill.gbr && \
        test -f test/output/gerbers/*PTH_drill.drl
    - uses: peter-evans/rebase@v1
      if: ${{ success() }}
      with:
        base: develop
    - name: git commit && git push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ${{ github.workflow }} ${{ github.job }}
        push-branch: 'develop'
        files: test/output/gerbers/*

  plot:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: gerbers
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c plot.kibot.yaml
      uses: ./
      with:
        config: config/plot.kibot.yaml
        dir: test/output
        schema: test/test.sch
        board: test/test.kicad_pcb
    - name: "check output: plot"
      run: |
        test -f test/output/docs/img/test-top.svg && \
        test -f test/output/docs/img/test-bottom.svg 
    - uses: peter-evans/rebase@v1
      if: ${{ success() }}
      with:
        base: develop
    - name: git commit && git push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ${{ github.workflow }} ${{ github.job }}
        push-branch: 'develop'
        files: test/output/docs/img/*

  position:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: plot
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c position.kibot.yaml
      uses: ./
      with:
        config: config/position.kibot.yaml
        dir: test/output
        schema: test/test.sch
        board: test/test.kicad_pcb
    - name: "check output: position"
      run: |
        test -f test/output/gerbers/*pos*.csv
    - uses: peter-evans/rebase@v1
      if: ${{ success() }}
      with:
        base: develop
    - name: git commit && git push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ${{ github.workflow }} ${{ github.job }}
        push-branch: 'develop'
        files: test/output/gerbers/*

  cad:
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: position
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: kicad-exports -c cad.kibot.yaml
      uses: ./
      with:
        config: config/cad.kibot.yaml
        dir: test/output
        schema: test/test.sch
        board: test/test.kicad_pcb
    - name: "check output: cad"
      run: |
        test -f test/output/cad/*.step
    - uses: peter-evans/rebase@v1
      if: ${{ success() }}
      with:
        base: develop
    - name: git commit && git push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: ${{ github.workflow }} ${{ github.job }}
        push-branch: 'develop'
        files: test/output/cad/*
